entityName: 'Usuario'
entity: 'BloxSys\UsuariosBundle\Entity\Usuario'
repository: 'BloxSysUsuariosBundle:Usuario'
paginate: true
index: 'usuario'
view_index: 'BloxSysUsuariosBundle:usuario:index.html.twig'
new: 'usuario_new'
create: 'usuario_create'
view_new: 'BloxSysUsuariosBundle:usuario:new.html.twig'
edit: 'usuario_edit'
update: 'usuario_update'
view_edit: 'BloxSysUsuariosBundle:usuario:edit.html.twig'
show: 'usuario_show'
view_show: 'BloxSysUsuariosBundle:usuario:show.html.twig'
delete: 'usuario_delete'
export: 'usuario_export'
sessionFilter: 'UsuarioControllerFilter'
saveAndAdd: true
validator: true
fieldsindex:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        export: true
    a.login:
        label: 'Login'
        name: 'login'
        type: 'string'
        export: true
    a.password:
        label: 'Password'
        name: 'password'
        type: 'string'
        export: true
    a.dni:
        label: 'Dni'
        name: 'dni'
        type: 'string'
        export: true
    a.role:
        label: 'Role'
        name: 'role'
        type: 'string'
        export: true
    a.nombreCompleto:
        label: 'Nombrecompleto'
        name: 'nombreCompleto'
        type: 'string'
        export: true
    a.email:
        label: 'Email'
        name: 'email'
        type: 'string'
        export: true
    a.isActive:
        label: 'Isactive'
        name: 'isActive'
        type: 'boolean'
        export: true
    a.createdAt:
        label: 'Createdat'
        name: 'createdAt'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
    a.updatedAt:
        label: 'Updatedat'
        name: 'updatedAt'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'id'
        type: 'integer'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.login:
        label: 'Login'
        name: 'login'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.password:
        label: 'Password'
        name: 'password'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.dni:
        label: 'Dni'
        name: 'dni'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.role:
        label: 'Role'
        name: 'role'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.nombreCompleto:
        label: 'Nombrecompleto'
        name: 'nombreCompleto'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.email:
        label: 'Email'
        name: 'email'
        type: 'string'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.isActive:
        label: 'Isactive'
        name: 'isActive'
        type: 'boolean'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.createdAt:
        label: 'Createdat'
        name: 'createdAt'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12 col-md-12'
        #closerow: true
    a.updatedAt:
        label: 'Updatedat'
        name: 'updatedAt'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12 col-md-12'
        #closerow: true